server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称
  client:
    #    false表示不向注册中心注册自己
    register-with-eureka: false
    #    false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #      设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://eureka7001.com:7001/eureka/
  server:
    #自我保护机制 保证不可用服务及时清除(默认开启为true)
    enable-self-preservation: true
    #多少毫秒没收到心跳反应将及时剔除服务(默认为0)
    eviction-interval-timer-in-ms: 0