server:
  port: 80


spring:
  application:
    name: cloud-consumer-order
#Eureka配置
eureka:
  client:
    #    表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    #    是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    #    EurekaServer的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: zbn-80
    #此配置是为了让访问路径可以显示IP地址
    prefer-ip-address: true
    #心跳检测与续约时间
    #开发时设置小些，保证服务关闭后注册中心及时剔除服务
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 90