server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
  # Consul注册中心地址
  cloud:
    consul:
      host: 192.168.43.100
      port: 8500
      discovery:
        service-name: ${spring.application.name}
